### ISSUE TITLE
Add google analytics tracking

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-website#27]
Slack context: https://edgi.slack.com/archives/C3EF5T7T6/p1498851776482480

cc: @trinberg

**Comment by dcwalk** [comment]
I'm generally not a fan of web tracking analytics, but get that they have their place 

(this issue also makes me think of the theme we've run aground on in the Archiving side of how people only show engagement with federal data through website analytics and making sure they don't wind up standing in for something important).

**Comment by patcon** [comment]
I empathize. What if we allowed agency to opt-out via DNT header?

https://stackoverflow.com/questions/16947459/is-it-possible-to-check-the-value-of-firefox-dnt-with-javascript

**Comment by dcwalk** [comment]
Just circling back on this -- whatever we do should be consistent with the 100days report website. @shaqsingh and @patcon maybe we can have a convo about both?

**Comment by patcon** [comment]
Just did some related things:
- [x] created a Google Analytics account for EDGI through the envirodgi@gmail.com account
- [x] gave these google accounts full admin access: @patcon, @dcwalk, @lourdesvera, @shaqsingh 
- [x] created a sub-property for "EDGI Website" (`UA-106049718-1`) and "100 Days report" (`UA-106049718-2`)
- [x] updated [service access doc](https://paper.dropbox.com/doc/Services-Deployment-pTsHUVIb2JuFHo8KVfpq2)

**Comment by dcwalk** [comment]
@patcon can you send the invite to my google acct? Also we should invite Jamie

**Comment by patcon** [comment]
- [x] invite @dcwalk personal gmail
- [x] invite jamie lyons
- [x] update [services access doc](https://paper.dropbox.com/doc/Services-Deployment-pTsHUVIb2JuFHo8KVfpq2)
- [x] adjusted access control permissions (see service access doc)

Re: Google Analytics access. I basically just left "Manage Users" access perms with the main account, dcwalk, and I, but I'm open to sharing more widely. Also curious whether anyone understands GA better and has more thoughts on how to distribute access. I don't want to lock anyone out of things they need :)

**Comment by dcwalk** [comment]
Could you invite @lourdesvera? She and Jamie are joint communications leads

**Comment by patcon** [comment]
There was interest in this from Chris Sellers, Gretchen and others in the during op-ed workshop, on tracking incoming links from op-ed's to see what sort of engagement they might provoke.

**Comment by lourdesvera** [comment]
Done! We have google analytics tracking on the wordpress website.
